name: VNC Server with Backup to Google Drive

on:
  workflow_dispatch:

jobs:
  vnc-backup:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # Set the max runtime to 8 hours

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Desktop Environment and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies
          sudo apt-get install -y xorg dbus-x11 x11-xserver-utils

      - name: Install VNC Server
        run: |
          sudo apt-get install -y tigervnc-standalone-server tigervnc-xorg-extension
          mkdir -p ~/.vnc
          echo "password" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1280x720 -depth 24 -localhost no
          echo "VNC server started on :1"

      - name: Install noVNC
        run: |
          sudo apt-get install -y novnc websockify
          mkdir -p ~/novnc
          wget https://github.com/novnc/noVNC/archive/v1.2.0.tar.gz -O ~/novnc/novnc.tar.gz
          tar -xvzf ~/novnc/novnc.tar.gz -C ~/novnc --strip-components=1
          sudo ln -s ~/novnc/vnc.html ~/novnc/index.html
          
      - name: Start noVNC Server
        run: |
          websockify --web ~/novnc --wrap-mode=ignore 6080 localhost:5901 &

      - name: Install gdrive
        run: |
          wget -O gdrive https://drive.google.com/uc?id=1UPZJr1Wc4hLB7M5nR5dQXM5_WlxQicId
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/

      - name: Authenticate gdrive
        run: |
          echo "${{ secrets.GDRIVE_AUTH_JSON }}" > /tmp/credentials.json
          gdrive about --service-account /tmp/credentials.json

      - name: Backup Data to Google Drive
        run: |
          mkdir -p backup
          # Replace with commands to backup data from VNC session to 'backup' directory
          # Example: tar -czvf backup/backup.tar.gz /path/to/data
          tar -czvf backup/backup.tar.gz /path/to/data
          gdrive upload --recursive --service-account /tmp/credentials.json backup/
          echo "Backup completed."

      - name: Keep Session Alive
        run: |
          while true; do echo "Keeping session alive"; sleep 300; done
